coronatracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('coronatracker/admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from .views import (HomeView,
                    CountriesListView,
                    CountriesDetailView)

app_name = 'mainapp'

urlpatterns = [
    path('', HomeView, name='homepage'),
    path('countries/', CountriesListView, name='countries'),
    path('countries/<str:name>', CountriesDetailView, name="country_detail" )
]

mainapp/models.py
from django.db import models
from django.urls import reverse
from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
# Create your models here.


class Continent(models.Model):
    name = models.CharField(max_length=200)
    
    
    def get_absolute_url(self):
        return reverse("mainapp:category", kwargs={"name": self.name})
    
    def __str__(self):
        return self.name
class Region(models.Model):
    name = models.CharField(max_length=200)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE,
                                  blank=True, null=True)
    
    def get_absolute_url(self):
        return reverse("mainapp:region", kwargs={"name": self.name})
    
    def __str__(self):
        return self.name
    
class Country(models.Model):
    name = models.CharField(max_length=200)
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE, 
                                 related_name="country_category",
                                 null=True, blank=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE,
                               related_name="country_region",
                               blank=True, null=True)
    flag = models.ImageField(upload_to='images/country-flag', 
                             default='images/country-flag/hacker.jpg')
    flag_thumbnail = ImageSpecField(source='flag',
                                    processors = [ResizeToFill(300,150)],
                                    format='JPEG',
                                    options = {'quality':100})
    
    def get_absolute_url(self):    
        return reverse('mainapp:country_detail', kwargs={'name': self.name})
    
    def __str__(self):
        return self.name

mainapp/views.py
from django.shortcuts import render, get_object_or_404
import requests
from .models import Country
from django.db.models import Q

# Create your views here.

def HomeView(request, *args, **kwargs):
    url = "https://covid-193.p.rapidapi.com/statistics"

    querystring = {"country":"Kenya"}

    headers = {
        'x-rapidapi-key': "3309c51481msh3e38aacc1ee9fc3p1de04bjsn538e242cf931",
        'x-rapidapi-host': "covid-193.p.rapidapi.com"
        }

    response = requests.request("GET", url, headers=headers, params=querystring).json()

    data = response['response'][0]

    context = {
        'new':data['cases']['new'],
        'active':data['cases']['active'],
        'critical':data['cases']['critical'],
        'recovered':data['cases']['recovered'],
        'deaths':data['deaths']['total'],
        'new_deaths':data['deaths']['new'],
        'total':data['cases']['total'],
        'date_updated':data['day'],
        'time_updated':data['time']
        
    }
    
    return render(request, 'index.html', context)

def CountriesListView(request, *args, **kwargs):

    countries = Country.objects.all()
    
    query = request.GET.get('q', None)
    
    if query is not None:
       countries = Country.objects.filter(Q(name__icontains=query))
    
    context = {
        'countries':countries,
        
    }
    return render(request, 'countries.html', context)


def CountriesDetailView(request, name, *args, **kwargs):
    country = get_object_or_404(Country, name=name)
    
    url = "https://covid-193.p.rapidapi.com/statistics"

    querystring = {"country":f"{name}"}

    headers = {
        'x-rapidapi-key': "3309c51481msh3e38aacc1ee9fc3p1de04bjsn538e242cf931",
        'x-rapidapi-host': "covid-193.p.rapidapi.com"
        }

    response = requests.request("GET", url, headers=headers, params=querystring).json()

    data = response['response'][0]
  
    context = {
        'country':country,
        'new':data['cases']['new'],
        'active':data['cases']['active'],
        'critical':data['cases']['critical'],
        'recovered':data['cases']['recovered'],
        'deaths':data['deaths']['total'],
        'new_deaths':data['deaths']['new'],
        'total':data['cases']['total'],
        'date_updated':data['day'],
        'time_updated':data['time']
        
    }
       
    return render(request, 'country_detail.html', context)

def country_search(request, *args, **kwargs):
    pass

coronatracker/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="icon" href="{% static 'images/icon.jpg' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>R-Corona Tracker | 
    {% block title %}
        
    {% endblock title %}
    </title>
</head>


<body class="body"> 

    <nav class="navbar navbar-expand-md navbar-dark bg-info">
        <a href="{% url 'mainapp:homepage' %}" class="navbar-brand">ReTech Corona Statistics</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'mainapp:homepage' %}" class="nav-item nav-link active">Home</a>
                <a href="{% url 'mainapp:countries' %}" class="nav-item nav-link active">Countries</a>
                <a href="https://github.com/itsregalo" class="nav-item nav-link active">Products</a>
            </div>
            <form class="form-inline ml-auto">
                <input name='q' type="text" placeholder="eg. kenya" class="form-control mr-sm-2" placeholder="Search"
                value="{{ request.GET.q }}">
                <button type="submit" class="btn btn-outline-light">Search</button>
            </form>
        </div>
      </nav>
    {% block body %}
    
    {% endblock body %}

    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

coronatracker/templates/countries.html
{% extends 'base.html' %}

{% block title %}
    Countries
{% endblock title %}


{% block body %}

  <div class="text-center">
      <h3 style="color: white;" class="p-3 bg-info">Retech Coronavirus Statistics <span style="color: red;" >Live</span> </h3>
  </div>

<div class="container">

    <section class="wow fadeInUp">
      <div class="container">
        <div class="section-header">
          <h3 class="bg-info text-center">Countries [East Africa]</h3>
        </div>

        <div class="row">
          
          {% if countries %}

          
          {% for obj in countries %}
            <div class="col-lg-3 col-md-3 mb-6">
              <div class="country-card">
                <div class="card">
                  <div class="member bg-info">
                    <a href="{% url 'mainapp:country_detail' obj.name %}">
                      <div class="pic view overlay">    
                        {% if obj.flag %}
                          <img class="card-img-top" src="{{ obj.flag_thumbnail.url }}" alt="{{ obj.name }}">
                        {% endif %}      
                      </div>
                      <div class="card-body">
                        <h3><a class="text-light" href="{% url 'mainapp:country_detail' obj.name %}">{{ obj.name }}</a></h3>
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
            

          {% else %}
          <div>
            <h3>No Entries yet</h3>
          </div>
          {% endif %}
          

        </div>

      </div>
    </section>


</div>
<footer>
<div class="text-center">
    <p class="bg-info"> Developed by <a href="https://github.com/itsregalo">itsregalo</a> .</p>
</div>

</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock body %}
    
    

coronatracker/templates/country_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
        {{ country.name }}
{% endblock title %}
{% block body %}

<div class="text-center">
  <h3 style="color: white;" class="p-3 bg-info">Retech Coronavirus Tracker ({{ country.name }})<span style="color: red;" >Live</span> </h3>
</div>


<div class="container">

    <section id="counter" class="section-padding">
        <div class="overlay"></div>
        <div class="container">
          <div class="row justify-content-between">
            <div class="col-lg-12 col-md-12 col-xs-12">
              <div class="mt-4 text-center row">
                <!-- Start counter -->
                <div class="bg-danger mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ total }}</b> </span></h2>
                      <h3>All Cases</h3>
                    </div>
                  </div>
                </div>
                <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-warning mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ active }}</b> </span></h2>
                      <h3>Active Cases</h3>
                    </div>
                  </div>
                </div>
                <!-- End counter -->
                <!-- Start Counter -->
                <div class="bg-info mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ critical }}</b> </span></h2>
                      <h3>Critical Cases</h3>
                    </div>
                  </div>
                </div>
              <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-success mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                    <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                      <div class="icon-o"><i class="lni-users"></i></div>
                      <div class="fact-count">
                        <h2><span class="counter"> <b>{{ recovered }}</b> </span></h2>
                        <h3>Recovered</h3>
                      </div>
                    </div>
                  </div>
                <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-secondary mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                    <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                      <div class="icon-o"><i class="lni-users"></i></div>
                      <div class="fact-count">
                        <h2><span class="counter"> <b>{{ deaths }}</b> </span></h2>
                        <h3>Total Deaths</h3>
                      </div>
                    </div>
                  </div>
                <!-- End Counter -->
              <!-- Start counter -->
              <div class="bg-danger mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                  <div class="icon-o"><i class="lni-users"></i></div>
                  <div class="fact-count">
                    <h2><span class="counter"> <b>{{ new_deaths }}</b> </span></h2>
                    <h3>New Deaths</h3>
                  </div>
                </div>
              </div>
              <!-- End counter -->
              <div class="bg-warning mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                  <div class="icon-o"><i class="lni-users"></i></div>
                  <div class="fact-count">
                    <h2><span class="counter"> <b>{{ new }}</b> </span></h2>
                    <h3>New Cases</h3>
                  </div>
                </div>
              </div>


          </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Counter Section End -->
      <div class="bg-success">
        <h5 class="text-center">Last Updated on {{ date_updated }}</h5>
      </div>

</div>
<footer>
    <div class="text-center">
        <p class="bg-success"> Developed by <a href="https://github.com/itsregalo">itsregalo</a> .</p>
    </div>
    
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock body %}
    
    

coronatracker/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
        Home
{% endblock title %}
{% block body %}
<div class="text-center">
  <h3 style="color: white;" class="p-3 bg-info">Retech Coronavirus Tracker (KENYA)<span style="color: red;" >Live</span> </h3>
</div>



<div class="container">

    <section id="counter" class="section-padding">
        <div class="overlay"></div>
        <div class="container">
          <div class="row justify-content-between">
            <div class="col-lg-12 col-md-12 col-xs-12">
              <div class="mt-4 text-center row">
                <!-- Start counter -->
                <div class="bg-danger mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ total }}</b> </span></h2>
                      <h3>All Cases</h3>
                    </div>
                  </div>
                </div>
                <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-warning mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ active }}</b> </span></h2>
                      <h3>Active Cases</h3>
                    </div>
                  </div>
                </div>
                <!-- End counter -->
                <!-- Start Counter -->
                <div class="bg-info mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                  <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                    <div class="icon-o"><i class="lni-users"></i></div>
                    <div class="fact-count">
                      <h2><span class="counter"> <b>{{ critical }}</b> </span></h2>
                      <h3>Critical Cases</h3>
                    </div>
                  </div>
                </div>
              <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-success mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                    <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                      <div class="icon-o"><i class="lni-users"></i></div>
                      <div class="fact-count">
                        <h2><span class="counter"> <b>{{ recovered }}</b> </span></h2>
                        <h3>Recovered</h3>
                      </div>
                    </div>
                  </div>
                <!-- End counter -->
                <!-- Start counter -->
                <div class="bg-secondary mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                    <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                      <div class="icon-o"><i class="lni-users"></i></div>
                      <div class="fact-count">
                        <h2><span class="counter"> <b>{{ deaths }}</b> </span></h2>
                        <h3>Total Deaths</h3>
                      </div>
                    </div>
                  </div>
                <!-- End Counter -->
              <!-- Start counter -->
              <div class="bg-danger mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                  <div class="icon-o"><i class="lni-users"></i></div>
                  <div class="fact-count">
                    <h2><span class="counter"> <b>{{ new_deaths }}</b> </span></h2>
                    <h3>New Deaths</h3>
                  </div>
                </div>
              </div>
              <!-- End counter -->
              <div class="bg-warning mb-3 m-2 rounded-lg p-3 col-lg-3 col-md-6 col-xs-12">
                <div class="counter-box wow fadeInUp" data-wow-delay="0.2s">
                  <div class="icon-o"><i class="lni-users"></i></div>
                  <div class="fact-count">
                    <h2><span class="counter"> <b>{{ new }}</b> </span></h2>
                    <h3>New Cases</h3>
                  </div>
                </div>
              </div>


          </div>
            </div>
          </div>
        </div>
      </section>
      <!-- Counter Section End -->
      <div class="bg-info">
        <h5 class="text-center">Last Updated on {{ date_updated }}</h5>
      </div>

</div>
<footer>
    <div class="text-center">
        <p class="bg-info"> Developed by <a href="https://github.com/itsregalo">itsregalo</a> .</p>
    </div>
    
</footer>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock body %}
    
    